### ISSUE TITLE
Get proper ICTA logo

### ISSUE THREAD

**Issue by jaybaeta** [jaybaeta/icta-2017#1]
Current logo is low-res and from 2016. Needs to be svg/hi-res png and 2017.

**Comment by w1lldone** [comment]
How about this?
![icta](https://cloud.githubusercontent.com/assets/19965509/25114501/43eb3c5e-2429-11e7-829e-3649e06838ad.png)

**Comment by jaybaeta** [comment]
Can we get it in svg, like ICST/ICHS?

**Comment by w1lldone** [comment]
Of course. I will tell Rafi.
