### ISSUE TITLE
Add photo credits

### ISSUE THREAD

**Issue by jaybaeta** [jaybaeta/icta-2017#18]
https://www.flickr.com/photos/cifor/32778603930; https://www.flickr.com/photos/james_wheeler/9909142064; https://www.flickr.com/photos/cgiarclimate/14104673257/in/gallery-ilri-72157651071496591; https://www.flickr.com/photos/dbooster/15900757710; and https://www.flickr.com/photos/postflowersyndroms/7920883928 or https://www.flickr.com/photos/cifor/12184243296 depending on vote.

**Comment by jaybaeta** [comment]
Second image for Sustainable Tropical Forestry wins vote, so also change this symposium's image to that one.

**Comment by w1lldone** [comment]
![image](https://cloud.githubusercontent.com/assets/19965509/26090121/08ddaec0-3a2d-11e7-9962-4b865aaa5bb9.png)
is this okay?

**Comment by w1lldone** [comment]
Symposia images by <a href="https://www.flickr.com/photos/cifor/32778603930">Juan Carlos Huayllapuma/CIFOR</a>, <a href="https://www.flickr.com/photos/james_wheeler/9909142064">James Wheeler</a>, <a href="https://www.flickr.com/photos/cgiarclimate/14104673257/in/gallery-ilri-72157651071496591">C. Schubert (CCAFS)</a>, <a href="https://www.flickr.com/photos/dbooster/15900757710">David A. LaSpina</a>, and <a href="https://www.flickr.com/photos/cifor/12184243296">Ricky Martin for Center for International Forestry Research</a>

**Comment by w1lldone** [comment]
Is that okay?

**Comment by w1lldone** [comment]
Forestry image has been replaced #23

**Comment by jaybaeta** [comment]
All good. Thanks, @w1lldone.
