### ISSUE TITLE
Add ePaper guidebook and tutorials

### ISSUE THREAD

**Issue by jaybaeta** [jaybaeta/icta-2017#28]
Add the ePaper guidebook to relevant pages.

- [x] Add registration tutorial; link to this from PRESENTERS and NON-PRESENTERS.
- [x] Add abstract tutorial; link to this from PRESENTERS.
- [x] Add full paper tutorial; link to this from PRESENTERS.
- [x] Add ePaper guidebook to all three pages and author guidelines.
- [x] Add ePaper guidebook to PRESENTERS, NON-PRESENTERS, and DOWNLOADS in navbar.
- [x] Add ePaper guidebook to downloads page.

**Comment by w1lldone** [comment]
- [ ] list
